version: '3'
services:
  backend:
    image: simpleservices/auth-service:latest
    build: .
    ports:
    - "5000:5000"
    external_links:
    - postgres
      #environment:
      #- en"APP_SETTINGS=project.server.config.ProductionConfig"
  postgres:
    image: postgres:11
    ports:
    - "5432:5432"
    environment:
    - "POSTGRES_PASSWORD=test123"
    - "POSTGRES_DB=flask_jwt_auth"
    - "PGPASSWORD=test123"
